# Generated by Django 5.2.3 on 2025-06-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("genres", models.CharField(max_length=255)),
                (
                    "release_date",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("vote_average", models.FloatField(blank=True, null=True)),
                ("overview", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
